from typing import Protocol
from uuid import UUID


class ObservationContract(Protocol):
    def run_started(self, run_id: UUID, runtime: str) -> None: ...
    def run_succeeded(self, run_id: UUID, runtime: str, duration_seconds: float) -> None: ...
    def run_failed(self, run_id: UUID, runtime: str, duration_seconds: float) -> None: ...
