import subprocess
from pathlib import Path

import pytest

from agent_platform.worker.change_set import (
    ChangeSetBuilder,
)
from agent_platform.worker.workspace import (
    DisposableWorkerWorkspace,
)


def git(
    repo: Path,
    *args: str,
) -> str:
    result = subprocess.run(
        ["git", *args],
        cwd=repo,
        check=True,
        capture_output=True,
        text=True,
    )

    return result.stdout.strip()


@pytest.fixture
def remote_repo(
    tmp_path: Path,
) -> tuple[Path, str]:
    remote = tmp_path / "remote.git"

    subprocess.run(
        ["git", "init", "--bare", str(remote)],
        check=True,
        capture_output=True,
        text=True,
    )

    seed = tmp_path / "seed"
    seed.mkdir()

    git(seed, "init", "-b", "main")

    (seed / "README.md").write_text(
        "# baseline\n",
        encoding="utf-8",
    )

    git(seed, "add", ".")

    git(
        seed,
        "-c",
        "user.name=Test",
        "-c",
        "user.email=test@example.invalid",
        "commit",
        "-m",
        "baseline",
    )

    git(
        seed,
        "remote",
        "add",
        "origin",
        str(remote),
    )

    git(
        seed,
        "push",
        "-u",
        "origin",
        "main",
    )

    revision = git(
        seed,
        "rev-parse",
        "HEAD",
    )

    return remote, revision


def test_workspace_is_fresh_and_removed(
    tmp_path: Path,
    remote_repo: tuple[Path, str],
) -> None:
    remote, revision = remote_repo
    parent = tmp_path / "workspaces"

    manager = DisposableWorkerWorkspace(
        repository_url=str(remote),
        workspace_parent=parent,
    )

    with manager.open() as workspace:
        assert workspace.path.exists()
        assert workspace.base_revision == revision

        assert (
            git(
                workspace.path,
                "status",
                "--porcelain",
            )
            == ""
        )

    assert list(parent.iterdir()) == []


def test_workspace_is_removed_when_worker_fails(
    tmp_path: Path,
    remote_repo: tuple[Path, str],
) -> None:
    remote, _ = remote_repo
    parent = tmp_path / "workspaces"

    manager = DisposableWorkerWorkspace(
        repository_url=str(remote),
        workspace_parent=parent,
    )

    with pytest.raises(
        RuntimeError,
        match="worker failed",
    ):
        with manager.open():
            raise RuntimeError("worker failed")

    assert list(parent.iterdir()) == []


def test_workspace_builds_change_set_before_cleanup(
    tmp_path: Path,
    remote_repo: tuple[Path, str],
) -> None:
    remote, revision = remote_repo
    parent = tmp_path / "workspaces"

    manager = DisposableWorkerWorkspace(
        repository_url=str(remote),
        workspace_parent=parent,
    )

    with manager.open() as workspace:
        (workspace.path / "worker-output.txt").write_text(
            "generated by worker\n",
            encoding="utf-8",
        )

        change_set = ChangeSetBuilder(workspace.path).build(
            branch_name="agent/worker-test",
            commit_message="feat: worker test",
        )

        assert change_set.base_revision == revision

        assert change_set.changed_paths == ("worker-output.txt",)

        assert change_set.changes[0].content == "generated by worker\n"

    assert list(parent.iterdir()) == []
